api/urls.py
from django.urls import path, include

from .views import (UserView,
                    QuestionsListView, 
                    QuizListView,QuizView,
                    QuestionsListQuizView,
                    QuestionCreateView, 
                    AnswersListView,
                    
                    QuestionView)

urlpatterns = [
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('user/', UserView.as_view(), name='user'),
    path('questions/', QuestionsListView.as_view(), name='questions'),
    path('question/<int:pk>/', QuestionView.as_view(), name='question'),
    path('answers/<int:pk>/', AnswersListView.as_view(), name='answers-delete'),
    path('question/<int:pk>/answers/', AnswersListView.as_view(), name='answers'),
    path('question/', QuestionCreateView.as_view(), name='question-create'),


    path('quizzes/', QuizListView.as_view(), name='quizzes'),
    # path('quiz/', PostQuizView.as_view(), name='quiz-post'),
    path('quiz/<int:pk>/questions/', QuestionsListQuizView.as_view(), name='questions-quiz'),
    path('quiz/<int:pk>/', QuizView.as_view(), name='quiz'),

]

main/urls.py
from django.urls import path
from .views import (
    QuizzesList,
    QuizzesListAdmin,
    quiz_detail,
    quiz_data,
    quiz_result,
    quiz_create,
    quiz_update, 
    quize_delete,
    quiz_questions,
    question_create,
    question_ansewrs,
    answer_create,
    quiz_detail_admin,
    index
)

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('quiz/',QuizzesList.as_view() , name='quiz_list'),
    path('quiz/admin/',QuizzesListAdmin.as_view() , name='quiz_list_admin'),

    path('quiz/<int:pk>/', quiz_detail, name='quiz_detail'),
    path('quiz/<int:pk>/data/', quiz_data, name='quiz_data'),
    path('quiz/<int:pk>/results/', quiz_result, name='quiz_results'),
    path('quiz/create/', quiz_create, name='quiz_create'),
    path('quiz/admin/<int:pk>/update/', quiz_update, name='quiz_update'),
    path('quiz/admin/<int:pk>/delete/', quize_delete, name='quiz_delete'),
    path('quiz/admin/<int:pk>/details/', quiz_detail_admin, name='quiz_detail_admin'),
    path('quiz/admin/<int:pk>/details/questions/', quiz_questions, name='quiz_questions'),
    path('quiz/admin/<int:pk>/details/questions/<int:pk_question>/answers/', question_ansewrs, name='question_answers'),
    path('quiz/admin/<int:pk>/details/questions/<int:pk_question>/answers/create/', answer_create, name='question_answers-create'),


    path('quiz/admin/<int:pk>/update/question/create/', question_create, name='question_create'),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('connect.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from connect.models import User
# from django.contrib.auth.models import User

QUESTION_TYPE = (
        ('MCQ', 'Multiple Choice'),
        ('TF', 'True or False'),
        ('FIB', 'Fill in the Blank'),
        )
        

class Quiz(models.Model):
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True)
    topic = models.CharField(max_length=200)
    number_of_questions = models.IntegerField(default=0)
    time = models.IntegerField(help_text="Time in minutes", default=0)
    required_score = models.IntegerField(help_text="Score required to pass the quiz")

    def __str__(self):
        return self.name

    def get_questions(self):
        return self.question.all()[:self.number_of_questions]

class Question(models.Model):
    question_type = models.CharField(max_length=50, choices=QUESTION_TYPE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="question")
    text = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
        

    def __str__(self):
        return self.text

    def get_answers(self):
        return self.answer.all()
    


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usrt_answer")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answer')
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    cereated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="result")
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    score = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

main/forms.py
from django.forms import ModelForm
from .models import Quiz, Question, Answer



# create form for Quiz model (create quiz) 
class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = [ 'name', 'topic', 'number_of_questions', 'time', 'required_score']

    
# cerate form for Quiz model (edit quiz)
class QuizEditForm(ModelForm):
    class Meta:
        model = Quiz
        fields = ['name', 'topic', 'number_of_questions', 'time', 'required_score']

# # create form for Question model (create question)
class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_type', 'text']

# create form for Answer model (create answer)
class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['user', 'question', 'text', 'correct']

# crete form for delete quiz

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import User, Quiz, Question, Answer, Result
from django.views.generic import ListView
from django.http import JsonResponse, HttpResponseRedirect
from .forms import QuizForm, QuizEditForm,QuestionForm, AnswerForm
from django.contrib import messages
from django.shortcuts import get_object_or_404, get_list_or_404
from .decorators import allowed_users
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt,csrf_protect #Add this




# from rest_framework.views import APIView


def index(request):
    user_group = []
    for group in request.user.groups.all():
        user_group.append(group.name)
    print("user_group = ",user_group)
    context = {
        "user_group" : user_group,
    }    
    return render(request, 'templates/index.html', context=context)

# __________/ for students \____________
class QuizzesList(ListView):
    model = Quiz
    template_name = 'templates/quizzes.html'
# __________/ for admin \____________
class QuizzesListAdmin(ListView):
    model = Quiz
    template_name = 'templates/admin_quizzes.html'

    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(QuizzesListAdmin, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['quizzes'] = Quiz.objects.filter(admin=self.request.user)
        return context    


# __________/ for quiz details \____________
def quiz_detail(request, pk):
    questions_length = get_object_or_404(Quiz, pk=pk).get_questions().count()
    context = {
        'questions_length' : questions_length,
        'quiz': get_object_or_404(Quiz, pk=pk)
    }
    return render(request, 'templates/quize_details.html', context)        

def quiz_detail_admin(request, pk):
    quiz = Quiz.objects.get(pk=pk, admin=request.user)
    context = {
        'quiz': quiz
    }
    return render(request, 'templates/quiz_details_admin.html', context)


# __________/ for quiz options \____________
def quiz_data(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    questions = []
    for question in quiz.get_questions():
        # questions.append(qu estion.text)
        answers = []
        for answer in question.get_answers():
            answers.append(answer.text)

        questions.append({str(question):answers})
    
    return JsonResponse({
        'questions': questions,
        'time' : quiz.time,
        })

def quiz_result(request, pk):
    # check if the request is ajax 
    if request.is_ajax():
        questions = []
        results = []
        correct_answers = None
        score = 0
        
        # get pos data from ajax request
        data = request.POST
        data = data.dict()
        data.pop('csrfmiddlewaretoken')
        
        # append all post data questions to the questions list
        for key in data.keys():
            quiz =get_object_or_404(Quiz, pk=pk)
            question = get_object_or_404(Question, text=key)
            questions.append(question)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)
        try:
            multiple_answers = 100 / len(questions)
        except ZeroDivisionError:
            multiple_answers = 0
        # loop over questions 
        for question in questions:
            # get the selected answer
            selected_answer = request.POST.get(question.text)
            # check if the answer is not empty 
            if selected_answer != "" :
                # get the question of the selected answer
                questins_of_answer = Answer.objects.filter(question=question)
                # loop over the answers of the question
                for answer in questins_of_answer:
                    # check if the selected answer is the same as the answer
                    if selected_answer == answer.text:
                        # check if the answer is correct
                        if answer.correct:
                            score += 1 
                            correct_answers = answer.text
                    else:
                        if answer.correct:
                            correct_answers = answer.text  
                # append the result to the results list if the answer is correct and not none
                results.append({question.text : {'correct_answer': correct_answers, 'answered': selected_answer}})                  
            else:
                # get the correct answer of the question
                questins_of_answer = Answer.objects.filter(question=question) 
                for answer in questins_of_answer:
                    if answer.correct:
                        correct_answer = answer.text 
                results.append({question.text :  {'correct_answer': correct_answer, 'answered': 'awnser not found'}}) 

        # calculate the score 
        _score = score * multiple_answers
        # save the result to the database
        Result.objects.create(user=user, quiz=quiz, score=_score)

        
        if _score >= quiz.required_score:
            return JsonResponse({'passed': True, 'score': _score, 'results': results})
        else:
            return JsonResponse({'passed': False,'score': _score, 'results': results})   


# __________/ for quiz options \____________
def quiz_create(request):
    if request.method == 'POST':
        form = QuizForm(request.POST)
        form.instance.admin = request.user
        if form.is_valid():
            form.changed_data
            form.save()
            pk = form.instance.id
            messages.success(
                request, f'Quiz is create successfuly for ')
            return redirect('main:question_create', pk=pk)    
        else:
            messages.success(request, f'Failed to create Quiz ')           
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))    
    if request.method == 'GET':

        form = QuizForm()
    return render(request, 'templates/quiz_create.html', {'form': form})

def quiz_update(request, pk):
    if request.method == 'POST':
        quiz = get_object_or_404(Quiz, pk=pk)

        form = QuizEditForm(request.POST, instance=quiz)
        if form.is_valid():
            obj = form.save(commit= False)
            obj.save()
            messages.success(
            request, f'Quiz is updated successfuly for {quiz.name}')
            context= {'form': form}

            return redirect('main:quiz_list_admin')
        else:
            print("form not valid" ,form.errors)
            messages.error(
            request, f'Failed to update {quiz.name}')
            return redirect('main:quiz_detail_admin')

    else:
        quiz = Quiz.objects.get(pk=pk)
        form = QuizEditForm(instance=quiz) 

        context = {
            'quiz': quiz,
            'form': form
        }
        return render(request, 'templates/quiz_update.html', context)

def quize_delete(request,pk):
    if request.method == 'POST':
        quiz = get_object_or_404(Quiz, pk=pk)
        quiz.delete()
        messages.success(
            request, f'Quiz is deleted successfuly for {quiz.name}')
        return redirect('main:quiz_list_admin')
    else:
        quiz = Quiz.objects.get(pk=pk)
        context = {'quiz' : quiz}
        return render(request, 'templates/quiz_delete.html', context)

def quiz_questions(request, pk):
    
    quiz = get_object_or_404(Quiz, pk=pk)
    questions = quiz.get_questions()
    print('hhh ',questions)
    context = {
        'quiz': quiz,
        'questions': questions,
        
    }
    return render(request, 'templates/quiz_questions.html', context)


# __________/ for question options \____________
def question_create(request, pk):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        form.instance.quiz = get_object_or_404(Quiz, pk=pk)

        if form.is_valid():
            form.save()
            messages.success(
                request, f'Question is create successfuly for ')
            return redirect('main:quiz_questions', pk=pk)
        else:
            print("form not valid")
            return redirect('main:quiz_detail_admin', pk=pk)    
    if request.method == 'GET':
        form = QuestionForm(request.POST)
        form = QuestionForm()
        quiz = get_object_or_404(Quiz, pk=pk)
        quizzes = Quiz.objects.all()
        quiz_choice = []
        for q in quizzes:
            if q.id == pk:
                quiz_choice.append(q.id)
                quiz_choice.append(q.name)
        context = {
            'form': form,
            'quiz': quiz,
            'quiz_choice': quiz_choice
            }
    return render(request, 'templates/question_create.html',context=context )

def question_ansewrs(request, pk, pk_question):
    
    quiz = Quiz.objects.get(pk=pk)
    question = get_object_or_404(Question, pk=pk_question)
    print('*****  ',question)


    context = {
        'question': question,
        'quiz_pk' : pk,
        'pk_question':pk_question
    }
    return render(request, 'templates/question_answers.html', context)        

@csrf_exempt
def answer_create(request, pk, pk_question):
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        form.instance.user = request.user
        
       

        if form.is_valid():
            form.save()
            messages.success(
                request, f'Answer is create successfuly  ')
            return redirect(f'/quiz/admin/{pk}/details/questions/{pk_question}/answers/')
        else:
            print("form not valid")
            return redirect('main:quiz_detail_admin', pk=pk)

    else:
        form = AnswerForm()
        questions = Question.objects.filter(quiz=pk)
        context = {
            'pk_question':pk_question,
            'form': form,
            'questions': questions,
        }

main/templates/sections/footer.html
<footer class="bg-dark text-center text-white footer ">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
                    <!-- Facebook -->
                    <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                    class="fab fa-facebook-f"></i></a>

                    <!-- Twitter -->
                    <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                    class="fab fa-twitter"></i></a>

                    <!-- Google -->
                    <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                    class="fab fa-google"></i></a>

                    <!-- Instagram -->
                    <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                    class="fab fa-instagram"></i></a>

                    <!-- Linkedin -->
                    <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                    class="fab fa-linkedin-in"></i></a>

                    <!-- Github -->
                    <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i
                                    class="fab fa-github"></i></a>
            </section>
            <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color:#003140 !important;">
            © 2021 Copyright:
            <a class="text-white" href="#">Yani</a>
    </div>
    <!-- Copyright -->
</footer>

main/templates/sections/header.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark"
    style="background-color:#010409 !important;">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="navbar-brand" href="">
                    <img src="/static/images/logo.png" height="35">
                </a>
                <a class="navbar-brand" href="{% url 'main:index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>

    <div class="mx-auto order-0">
        {%if request.user.is_authenticated%}
            <a class="navbar-brand mx-auto" id="username_header" href="">{{request.user.username}} {%if user_group%}  : <b style="color: #00b2df;"> {{user_group.0}} </b> {%endif%} </a>
        {%endif%}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    </div>

    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">            
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}    
                <li class="nav-item">
                    {% if 'students' in  user_group %}    
                        <a class="nav-link" href="{% url 'main:quiz_list' %}">Quizzes</a>
                    {%endif%}

                    {% if 'admin' in user_group%}
                        <a class=" nav-link" href="{% url 'main:quiz_list_admin' %}">Quizzes</a>
                    {%endif%}
                </li>
            {%endif%}   
            
            {%if user.is_authenticated%}
                <li class="nav-item">
                    <a class=" nav-link" href="{% url 'profile' %}"> Profile</a>
                </li>
                <li class="nav-item">
                    <a class=" nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {%else%}
                <li class="nav-item">
                    <a class=" nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class=" nav-link" href="{% url 'signup' %}">Signup</a> 
                </li>
            {%endif%}
        </ul>  
    </div>
</nav>