api/urls.py
from django.urls import path, include

from .views import (UserView,
                    QuestionsListView, 
                    QuizListView,QuizView,
                    QuestionsListQuizView,
                    QuestionCreateView, 
                    AnswersListView,
                    
                    QuestionView)

urlpatterns = [
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('user/', UserView.as_view(), name='user'),
    path('questions/', QuestionsListView.as_view(), name='questions'),
    path('question/<int:pk>/', QuestionView.as_view(), name='question'),
    path('answers/<int:pk>/', AnswersListView.as_view(), name='answers-delete'),
    path('question/<int:pk>/answers/', AnswersListView.as_view(), name='answers'),
    path('question/', QuestionCreateView.as_view(), name='question-create'),


    path('quizzes/', QuizListView.as_view(), name='quizzes'),
    # path('quiz/', PostQuizView.as_view(), name='quiz-post'),
    path('quiz/<int:pk>/questions/', QuestionsListQuizView.as_view(), name='questions-quiz'),
    path('quiz/<int:pk>/', QuizView.as_view(), name='quiz'),

]

main/urls.py
from django.urls import path
from .views import (
    QuizzesList,
    QuizzesListAdmin,
    quiz_detail,
    quiz_data,
    quiz_result,
    quiz_create,
    quiz_update, 
    quize_delete,
    quiz_questions,
    question_create,
    question_ansewrs,
    answer_create,
    quiz_detail_admin,
    index
)

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('quiz/',QuizzesList.as_view() , name='quiz_list'),
    path('quiz/admin/',QuizzesListAdmin.as_view() , name='quiz_list_admin'),

    path('quiz/<int:pk>/', quiz_detail, name='quiz_detail'),
    path('quiz/<int:pk>/data/', quiz_data, name='quiz_data'),
    path('quiz/<int:pk>/results/', quiz_result, name='quiz_results'),
    path('quiz/create/', quiz_create, name='quiz_create'),
    path('quiz/admin/<int:pk>/update/', quiz_update, name='quiz_update'),
    path('quiz/admin/<int:pk>/delete/', quize_delete, name='quiz_delete'),
    path('quiz/admin/<int:pk>/details/', quiz_detail_admin, name='quiz_detail_admin'),
    path('quiz/admin/<int:pk>/details/questions/', quiz_questions, name='quiz_questions'),
    path('quiz/admin/<int:pk>/details/questions/<int:pk_question>/answers/', question_ansewrs, name='question_answers'),
    path('quiz/admin/<int:pk>/details/questions/<int:pk_question>/answers/create/', answer_create, name='question_answers-create'),


    path('quiz/admin/<int:pk>/update/question/create/', question_create, name='question_create'),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('connect.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

main/templates/templates/admin_quizzes.html
{% extends "layout/base.html" %}

{%load static%}
{%block script%} 
<script src="{% static 'admin.js' %}" defer></script>
 {%endblock script%}

{% block title %}
Admin
{% endblock title %}

{% block content%}
<div class="row ">
  <h1 class="col-sm" >Quizzes : </h1>
  <!-- <a class="nav-item nav-link" id="create_quiz" href="{% url 'main:quiz_create' %}">Create quiz</a> -->
</div>

<hr>
<div class="row">

  {% if quizzes|length == 0%}
    <img src="/static/images/empty-quiz.png/" class="rounded mx-auto d-block" style="width: 200px;margin:20px" alt="empty">
{% endif %}



  

  {% for quiz in quizzes %}
          <div class="modal fade " id="quizModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Start quiz ?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body" id="modal-confirm">
                    
                  </div>
                  <div class="modal-footer">
                    <button type="button" id="delete-button"  class="btn btn-danger" data-dismiss="modal">Delete</button>
                    <button type="button" id="update-button" class="btn btn-success">Update</button>
                    <button type="button" id="details-button" class="btn btn-dark">Details</button>

                  </div>
                </div>
              </div>
          </div>
          
          <button 
              class="btn btn-link modal-button btnquiz col-sm"
              data-pk="{{quiz.pk}}"
              data-admin = "{{quiz.admin}}"
              data-quize="{{quiz.name}}"
              data-questions="{{quiz.number_of_questions}}"
              data-time="{{quiz.time}}"
              data-pass="{{quiz.required_score}}"
              data-object-list = "{{object_list}}"
              data-toggle="modal" 
              data-target="#quizModal">

              {{quiz.name}}
          </button>
          <br>
            
        {% endfor %}
</div>

<div class="row ">
    
  <a class=" btn btn-success" style="margin: 15px;"   href="{% url 'main:quiz_create' %}">Create quiz</a>

</div>

{%endblock content%}

<script>
  var objectList = JSON.parse('{{ object_list }}');
  window.onload = function () {
    if(objectList.length == 0){
      document.getElementById("empty-quiz").innerHTML = "No quizzes created yet";
    }
  }  
</script>

main/templates/templates/create_answer.html
{% extends "layout/base.html" %}

{%load static%}
<!-- {%block script%} 
<script src="{% static 'admin.js' %}" defer></script>
 {%endblock script%} -->

{% block title %}

{% endblock title %}
{{question.text}} 
{% block content%}
    <div class="row ">
            <h1 class="col-sm" > create new answer : </h1>
            <!-- <a class="nav-item nav-link" id="create_quiz" href="/quiz/admin/{{quiz.id}}/update/question/create/">Create New answer</a> -->
    </div>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}    
        <fieldset class="form-group">
            
            <div class="form-group">
                <label for="username">User :</label>
                <select class="form-control" name="user" id="user">                    
                    <option value="{{request.user.id}}">{{request.user.username}}</option>
                </select>
            </div>



            <div class="form-group">
                <label for="username">Question :</label>
                <select class="form-control" name="question" id="question"> 
                    {% for q in questions %} 
                        {%if q.id == pk_question%}                  
                            <option value="{{q.id}}">{{q.text}}</option>
                        {%endif%}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="username">Text :</label>
                <input type="text" class="form-control" id="text" name="text" placeholder="text">
            </div>
            <div class="form-group">
                <label for="username">{{form.correct.label}} :</label>
                {{form.correct}}
            </div>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-success" type="submit" >
                Create
            </button>
        </div>
    </form>
      
    <!-- {{form.as_p}} -->
    
</div>

{%endblock content%}

main/templates/templates/index.html
{% extends "layout/base.html" %}

{% block title %}

helloworld

{% endblock title %}

{% block content%}

<h1 align="center">
  <a href="https://git.io/typing-svg">
    <img src="https://readme-typing-svg.herokuapp.com/?lines=Hello,+There!+👋;+I'm+Yassine+youcefi+;Backend+developer!&center=true&size=30">
  </a>
</h1>
<div align="center">
  <img alt="GIF" src="https://github.com/abhisheknaiidu/abhisheknaiidu/blob/master/code.gif?raw=true" width="500" height="320" />
</div>

<hr> 

<h1 align="center">
    <a href="https://git.io/typing-svg">
      <img src="https://readme-typing-svg.herokuapp.com/?lines=Django+code+challenge ;+Made+for+BRENCO+;Python!&center=true&size=30">
    </a>
  </h1>


{%endblock content%}

main/templates/templates/question_answers.html
{% extends "layout/base.html" %}

{%load static%}
<!-- {%block script%} 
<script src="{% static 'admin.js' %}" defer></script>
 {%endblock script%} -->

{% block title %}

{% endblock title %}
{{question.text}} 
{% block content%}
    <div class="row ">
            <h1 class="col-sm" >{{question.text}} </h1>
            <!-- <a class="nav-item nav-link" id="create_quiz" href="/quiz/admin/{{quiz.id}}/update/question/create/">Create New answer</a> -->
    </div>

    <hr>
      

    <div style="margin: 15px;">
        {% if question.get_answers|length > 0%}
            {% for answer in question.get_answers %}
                <ul class="list-group list-group-flush">
                    {% if answer.correct %}
                    <li class="list-group-item list-group-item-success">{{answer.text}}</li>
                    {% else %}
                    <li class="list-group-item list-group-item-danger">{{answer.text}}</li>
                    {% endif %}
                </ul>

                <br>
            {% endfor %}
        {% else %}
            <img src="/static/images/empty.png/" class="rounded mx-auto d-block" style="width: 300px;" alt="empty">
        {% endif %}
    </div>
    <div class="row ">
    
        <a class=" btn btn-success" style="margin: 15px;"   href="/quiz/admin/{{quiz_pk}}/details/questions/{{pk_question}}/answers/create/">Create answer</a>
        <a class="btn btn-danger" style="margin: 15px;"  href="/quiz/admin/{{quiz_pk}}/details/questions/">Return</a>
    
    </div>
</div>

{%endblock content%}

main/templates/templates/question_create.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}

helloworld

{% endblock title %}

{% block content%}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="col-sm">Create a new question for {{quiz.name}}</h1>
            
            <hr>
        </div>

       

    <hr>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post">
                {% csrf_token %}
                <div class="content" id="create-quize">
                    <!-- {% crispy form %} -->
                    <div class="form-group">
                    <label for="question_type">{{ form.question_type.label}}</label>
                    {{ form.question_type}}    

                </div>

                <div class="form-group">
                    <label for="text">{{form.text.label}}</label>
                    <input type="text" class="form-control" id="text" name="text" placeholder=" write answer choise text">
                </div>

                <div class="form-group">
                    <!-- <label for="quiz_choice">{{form.quiz.label}}</label>
                    <select id='quiz_choice' class="browser-default custom-select" name="quiz_choice">
                        <option value="{{quiz_choice.0}}">{{quiz_choice.1}}</option>
                        
                    </select> -->
                    <!-- {{ form.quiz }} -->

                </div>
                





                <button type="submit" class="btn btn-success" style="margin: 30px;">Create</button>
                <a class="btn btn-primary" id="quit_question" href="{% url 'main:quiz_list_admin' %}">Cancel</a>
                
            </div>    
            </form>
        </div>
    </div>
</div>



{%endblock content%}

main/templates/templates/quiz_create.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}
{% block title %}

helloworld

{% endblock title %}

{% block content%}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="col-sm">Create a new quiz</h1>
        </div>
        <hr>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="{% url 'main:quiz_create' %}" method="post">
                {% csrf_token %}
                <div class="content" id="create-quize">
                    {% crispy form %}

                <button type="submit" class="btn btn-success">Create</button>
                <a class="btn btn-danger" style="margin: 15px;"  href="{% url 'main:quiz_list_admin' %}">Return</a>

                </div>    
            </form>
        </div>
    </div>
</div>



{%endblock content%}

main/templates/templates/quiz_delete.html
{% extends "layout/base.html" %}


{% block title %}
    Delete Quiz
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 id="h1-delete">
                Delete Quiz <b>{{quiz.name}}</b> </h1>
            </div>
        </div>
        
        
        <form action="" method="POST">
        {% csrf_token %}
        <h5 class="modal-title" id="h5-delete" >Are you sure to delete <b>{{quiz.name}}</b> Quiz ?</h5>

        <button type="submit"  value="delete Post" class="btn btn-danger">Delete</button>

        </form>
        <br/><br/>

        
    </div>
{% endblock %}

main/templates/templates/quiz_details_admin.html
{% extends "layout/base.html" %}


{% block title %}
 {{quiz.name}}
{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="col-sm">
            Quiz : <b>{{quiz.name}}</b> </h1>
            
        </div>

    </div>
    <hr>


    <div class="row">
        <label for="username"><h2>Topic :</h2></label>
        <div class="col">
            <h4 class="col-sm" >
                {{quiz.topic}}
            </h4>
        </div>
    </div>

    <div class="row">
        <label for="username"><h2>number of questions :</h2></label>
        <div class="col">
            <h4 class="col-sm">
                {{quiz.number_of_questions}}
            </h4>
        </div>
    </div>

    <div class="row">
        <label for="username"><h2>time :</h2></label>
        <div class="col">
            <h4 class="col-sm">
                {{quiz.time}} min
            </h4>
        </div>
    </div>

    <div class="row">
        <label for="username"><h2>Score :</h2></label>
        <div class="col">
            <h4 class="col-sm">
                {{quiz.required_score}}
            </h4>
        </div>
    </div>    
</div>




<hr>


<div class="row ">
    
    <a class=" btn btn-success" style="margin: 15px;"   href="/quiz/admin/{{quiz.id}}/update/">Edit Quize</a>
    <a class="btn btn-danger" style="margin: 15px;"  href="/quiz/admin/{{quiz.id}}/delete/">Delete Quize</a>
    <a class="btn btn-dark" style="margin: 15px;" href="/quiz/admin/{{quiz.id}}/details/questions/">View questions</a>

</div>

{% endblock %}

main/templates/templates/quiz_questions.html
{% extends "layout/base.html" %}

{%load static%}
{%block script%} 
<script src="{% static 'admin.js' %}" defer></script>
 {%endblock script%}

{% block title %}
Admin
{% endblock title %}

{% block content%}
<div class="row ">
        <h1 class="col-sm" >{{quiz.name}} questions : </h1>
        <!-- <a class="nav-item nav-link" id="create_quiz" href="/quiz/admin/{{quiz.id}}/update/question/create/">Create New question</a> -->
      </div>

      <hr>
      <div class="row">

  
    {% for question in questions %}


        <div class="modal fade "  id="questionModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel"> {{question.text}}  </h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-question-body" id="modal-confirm">
                  
                </div>
                <div class="modal-footer">
                  <button type="button" id="cansel-button"  class="btn btn-danger" data-dismiss="modal">Cancel</button>
                  <button type="button" id="answer-button" class="btn btn-success">Answers</button>

                </div>
              </div>
            </div>
        </div>
        
        <button 
            class="btn btn-link modal-question-button btnquiz col-sm"
            data-pk="{{question.pk}}"
            data-question-type = "{{question.question_type}}"
            data-text="{{question.text}}"
            data-answers = "{{question.get_answers|length}}"
            data-toggle="modal" 
            data-target="#questionModal">

            {{question.text}}
        </button>
        <br>

        
          



    {% endfor %}
    
</div>

<br/>

<div class="row ">    
  <a class=" btn btn-success" style="margin: 15px;"   href="/quiz/admin/{{quiz.id}}/update/question/create/">Create Question</a>
  <a class="btn btn-danger" style="margin: 15px;"  href="/quiz/admin/{{quiz.id}}/details/">Return</a>

</div>

{%endblock content%}

main/templates/templates/quiz_update.html
{% extends "layout/base.html" %}
{% load crispy_forms_tags %}


{% block title %}
    Update Quiz
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1 class="col-sm" >Update {{quiz.name}} Quiz</h1>
            <a class="nav-item nav-link" id="create_quiz" href="{{request.url}} question/create/">Create Questions</a>
        </div>
        
        <hr>
        <div class="row"></div>
            <form action="" method="POST">
                {% csrf_token %}
                <div>
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter quiz name">
                </div>

                <div>
                    <label for="topic">Topic</label>
                    <input type="text" class="form-control" id="topic" name="topic" placeholder="Enter quiz topic">
                </div>

                <div style="margin-top: 20px;">
                    <label for="number_of_questions" >Number of questions</label>
                    <!-- <input type="number" class="form-control" id="number-of-questions" name="id_number_of_questions" placeholder="Enter quiz number of questions"> -->
                    {{ form.number_of_questions }}
                </div>

                <div>
                    <label for="time">Time </label>
                    <input type="number" class="form-control" id="time" name="time" placeholder="Enter quiz time">
                </div>

                <div style="margin: 20px;">
                    <label for="score">Score </label>
                    <!-- <input type="number" class="form-control" id="score" name="score" placeholder="Enter quiz store"> -->
                    {{ form.required_score }}
                </div>        







                <button class="btn btn-success" type="submit" >
                    Update
                </button> 
                <a class="btn btn-danger" style="margin: 15px;"  href="/quiz/admin/{{quiz.id}}/details/">Return</a>
           
            </form>
         </div>
        <br/><br/>

        <!-- <form action="{% url 'main:quiz_create' %}" method="post">
            {% csrf_token %}
            <div class="content" id="create-quize">
                {% crispy form %}

            <button type="submit"  value="Edit Post" class="btn btn-primary">Update</button>
            </div>    
        </form> -->
    </div>
{% endblock %}

main/templates/templates/quize_details.html
{% extends "layout/base.html" %}

{%load static%}
{%block script%} 
<!-- Optional JavaScript -->
<script id="quiz-script" imoji="{% static 'main/success' %}" src="{% static 'quiz.js' %}" defer></script>
{%endblock script%}


{% block title %}
{{quiz.name}}
{% endblock title %}

{% block content%}

<div class="row">
    <div class="col">
        <h1 class="col-sm" >{{quiz.name.upper}} </h1>
    </div>
    <div class="col">

    <b style="color: cornsilk ;"> score to pass: {{quiz.required_score}}%</b>
    </div>
    <hr>
    <div class="col text-right" style="color: cornsilk ;" id="time-div"></div>

</div>
<a class="btn btn-danger" style="margin: 15px;"  href="{% url 'main:quiz_list' %}">Return</a>




<hr>
{% if questions_length > 0  %}
<h2 >Questions :</h2>
<div id="form-div">
<form id="quiz-details-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-div"></div>
    <button id="quize-submit-button" 
            type="submit" 
            class="btn btn-success" style="margin: 30px;">
        Save
    </button>
    <a class="btn btn-primary" id="quit_question" href="{% url 'main:quiz_list' %}">Cancel</a>

</form>
</div>
<div id="score-div"></div>
<div id="results-div"></div>

</div>
{% else%}
<img src="/static/images/empty.png/" class="rounded mx-auto d-block" style="width: 300px;" alt="empty">
{% endif %}




{%endblock content%}

main/templates/templates/quizes.html
{% extends "layout/base.html" %}

{%load static%}
{%block script%} 
<!-- Optional JavaScript -->
<script src="{% static 'main.js' %}" defer></script>
{%endblock script%}

{% block title %}
Quizzes list
{% endblock title %}

{% block content%}
<div class="row ">
  <h1 class="col-sm" >Quizzes : </h1>
</div>

<hr>
<div class="row">
{% for quize in object_list %}
<!-- Modal -->
<div class="modal fade " id="quizeModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Start quize ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-confirm">
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Not yet</button>
          <button type="button" id="start-button" class="btn btn-success">Yes i'm ready</button>
        </div>
      </div>
    </div>
  </div>

  
    <button 
        class="btn btn-link modal-button btnquiz col-sm"
        data-pk="{{quize.pk}}"
        data-quize="{{quize.name}}"
        data-questions="{{quize.number_of_questions}}"
        data-time="{{quize.time}}"
        data-pass="{{quize.required_score}}"
        data-toggle="modal" 
        data-target="#quizeModal">

        {{quize.name}}
    </button>
    <br>
    
    
    {% endfor %}
  </div>

{%endblock content%}

main/templates/templates/quizzes.html
{% extends "layout/base.html" %}

{%load static%}
{%block script%} 
<!-- Optional JavaScript -->
<script src="{% static 'main.js' %}" defer></script>
{%endblock script%}

{% block title %}
Quizzes list
{% endblock title %}

{% block content%}
<div class="row "> 
  <h1 class="col-sm" >Quizzes : </h1>
</div>

<hr>
<div class="row">

{% for quize in object_list %}
<!-- Modal -->
<div class="modal fade " id="quizeModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Start quize ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-confirm">
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Not yet</button>
          <button type="button" id="start-button" class="btn btn-success">Yes i'm ready</button>
        </div>
      </div>
    </div>
  </div>

    <button 
        class="btn btn-link modal-button btnquiz col-sm"
        data-pk="{{quize.pk}}"
        data-quize="{{quize.name}}"
        data-questions="{{quize.number_of_questions}}"
        data-time="{{quize.time}}"
        data-pass="{{quize.required_score}}"
        data-toggle="modal" 
        data-target="#quizeModal">

        {{quize.name}}
    </button>
    <br>
    
    
    {% endfor %}
  </div>

{%endblock content%}